name: Build wheel

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Build wheel
      run: |
        del pyxll_jupyter-*-py3-none-any.whl
        python -m pip wheel --no-deps .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: |
          ./pyxll_jupyter-*-py3-none-any.whl

