name: Build wheel

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Update Environment
      shell: pwsh
      run: |
        $env:IS_RELEASE_TAG = If ("${{ github.ref_name }}" -match "^\d+.\d+.\d+$") {'true'} Else {'false'}
        echo "IS_RELEASE_TAG=$env:IS_RELEASE_TAG" >> $env:GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build wheel
      run: |
        del pyxll_jupyter-*-py3-none-any.whl
        python -m pip wheel --no-deps .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: |
          ./pyxll_jupyter-*-py3-none-any.whl

    - name: Trigger Pypi upload
      uses: peter-evans/repository-dispatch@v3
      if: ${{ env.IS_RELEASE_TAG == 'true' }}
      with:
        event-type: pypi-upload
        client-payload: |-
          {
            "run_id": "${{ github.run_id }}",
            "ref_name": "${{ github.ref_name }}"
          }
